apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clubhub-prod
resources:
  - ../../base
  - ../../services/cms-api
  - ../../services/api-gateway
  - ../../services/replay-service
  - ../../services/entropy-service
  - ../../services/pre-runtime

commonLabels:
  environment: production
