apiVersion: v1
kind: Service
metadata:
  name: entropy-service
  namespace: clubhub
  labels:
    app: entropy-service
    app.kubernetes.io/part-of: clubhub
spec:
  selector:
    app: entropy-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
