apiVersion: v1
kind: Service
metadata:
  name: replay-service
  namespace: clubhub
  labels:
    app: replay-service
    app.kubernetes.io/part-of: clubhub
spec:
  selector:
    app: replay-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
