apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clubhub-staging
resources:
  - ../../base
  - ../../services/cms-api
  - ../../services/api-gateway
  - ../../services/replay-service
  - ../../services/entropy-service
  - ../../services/pre-runtime

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cms-api
        namespace: clubhub-staging
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: cms-api

commonLabels:
  environment: staging
