#!/bin/bash
# ClubHub TV — Raspberry Pi player setup script
# Run as root on a fresh Raspberry Pi OS Lite (64-bit) image.
#
# Installs:
#   - Node.js 20 LTS
#   - PM2 process manager
#   - Log rotation config
#   - Systemd watchdog integration
#   - Data directories with correct permissions
#   - logrotate config
#   - Cron job for monthly partition maintenance reminder
#
# DOES NOT:
#   - Set SCREEN_ID / VENUE_ID — must be provided per-device by commissioning tool
#   - Install the player-runtime code itself — deployed via OTA update
#   - Configure WiFi — must be done before running this script
#
# Human misuse protection:
#   - Script is idempotent (safe to run twice)
#   - Refuses to run if SCREEN_ID is already set (device already commissioned)
#   - All data directories are owned by clubhub user, not root

set -euo pipefail

CLUBHUB_USER="clubhub"
DATA_DIR="/var/clubhub"
LOG_DIR="/var/log/clubhub"
PLAYER_DIR="/opt/clubhub/player"

echo "[setup] ClubHub TV player setup starting..."

# ── Guard: refuse if already commissioned ────────────────────────────────────
if [ -f "/etc/clubhub/screen.env" ]; then
  echo "[setup] ERROR: /etc/clubhub/screen.env exists — device appears already commissioned."
  echo "[setup] If you intend to re-commission, remove /etc/clubhub/screen.env and re-run."
  exit 1
fi

# ── System updates ────────────────────────────────────────────────────────────
apt-get update -qq
apt-get install -y --no-install-recommends \
  curl ca-certificates logrotate smartmontools \
  chromium-browser xdotool xinit openbox

# ── Node.js 20 LTS ───────────────────────────────────────────────────────────
if ! command -v node &>/dev/null || [[ "$(node --version)" != v20* ]]; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi

# ── PM2 ──────────────────────────────────────────────────────────────────────
npm install -g pm2 --quiet
pm2 startup systemd -u "$CLUBHUB_USER" --hp "/home/$CLUBHUB_USER" | tail -1 | bash || true

# ── User + directories ───────────────────────────────────────────────────────
id "$CLUBHUB_USER" &>/dev/null || useradd --system --create-home --shell /bin/bash "$CLUBHUB_USER"
install -d -o "$CLUBHUB_USER" -g "$CLUBHUB_USER" -m 750 \
  "$DATA_DIR" \
  "$DATA_DIR/corpus" \
  "$DATA_DIR/replay" \
  "$DATA_DIR/assets" \
  "$LOG_DIR" \
  "$PLAYER_DIR" \
  /etc/clubhub

# ── Log rotation ─────────────────────────────────────────────────────────────
cp "$(dirname "$0")/../logrotate.conf" /etc/logrotate.d/clubhub-player
chmod 644 /etc/logrotate.d/clubhub-player

# ── Screen config template ───────────────────────────────────────────────────
# Commissioning tool writes actual SCREEN_ID and VENUE_ID here.
cat > /etc/clubhub/screen.env.template <<'EOF'
# Generated by commissioning tool — do not edit manually
SCREEN_ID=
VENUE_ID=
CMS_API_URL=https://api.clubhub.tv
CORPUS_CACHE_DIR=/var/clubhub/corpus
REPLAY_CACHE_DIR=/var/clubhub/replay
ASSET_DIR=/var/clubhub/assets
CORPUS_POLL_INTERVAL_MS=60000
HEARTBEAT_INTERVAL_MS=30000
WEBSOCKET_PORT=7777
LOG_LEVEL=INFO
EOF
chmod 640 /etc/clubhub/screen.env.template

# ── Hardware watchdog (Pi-specific) ──────────────────────────────────────────
# Enables the BCM2835 hardware watchdog — kicks if kernel hangs.
# Separate from our application watchdog.
if [ -e /dev/watchdog ]; then
  if ! grep -q "dtparam=watchdog=on" /boot/config.txt 2>/dev/null; then
    echo "dtparam=watchdog=on" >> /boot/config.txt
    echo "[setup] Hardware watchdog enabled in /boot/config.txt (requires reboot)"
  fi
  # Set hardware watchdog timeout to 15s
  echo 'RuntimeWatchdogSec=15s' >> /etc/systemd/system.conf || true
fi

# ── HDMI force hotplug (Pi-specific) ─────────────────────────────────────────
# Prevents display output loss on HDMI reconnect
if [ -e /boot/config.txt ]; then
  if ! grep -q "hdmi_force_hotplug" /boot/config.txt; then
    echo "hdmi_force_hotplug=1" >> /boot/config.txt
    echo "hdmi_drive=2" >> /boot/config.txt
    echo "[setup] HDMI force hotplug configured"
  fi
fi

echo "[setup] Setup complete. Next steps:"
echo "  1. Run commissioning tool to write /etc/clubhub/screen.env"
echo "  2. Deploy player-runtime code to $PLAYER_DIR"
echo "  3. Run: pm2 start $PLAYER_DIR/ecosystem.config.js"
echo "  4. Run: pm2 save"
echo "  5. Reboot to activate hardware watchdog and HDMI config"
