/**
 * Authentication and identity types for ClubHub.
 *
 * Constitutional rules:
 * - SPONSOR_STAKEHOLDER: zero mutation authority, zero emergency authority
 * - SERVICE scope is orthogonal to role hierarchy
 * - All mutations carry operator identity for audit
 */

// ─── Roles ───────────────────────────────────────────────────────────────────

export type UserRole =
  | 'PLATFORM_ADMIN'
  | 'ENTERPRISE_ADMIN'
  | 'REGIONAL_MANAGER'
  | 'VENUE_OPERATOR'
  | 'SPONSOR_STAKEHOLDER'
  | 'AUDITOR';

// ─── Scopes ──────────────────────────────────────────────────────────────────

/**
 * SERVICE scope: used by automated systems (entropy scheduler, shadow runner).
 * Orthogonal to user role hierarchy — not a "role" but a separate auth path.
 */
export type Scope =
  | 'USER'       // human operator — uses UserRole for permissions
  | 'SERVICE';   // automated service account — uses service_name for permissions

// ─── Tenancy ─────────────────────────────────────────────────────────────────

export interface TenantContext {
  readonly enterprise_id: string | null;    // null for PLATFORM_ADMIN (cross-tenant)
  readonly regional_org_id: string | null;
  readonly venue_id: string | null;
}

// ─── JWT Claims ──────────────────────────────────────────────────────────────

/** Claims embedded in JWT for human operators. */
export interface UserClaimsPayload {
  readonly sub: string;                     // user_id
  readonly scope: 'USER';
  readonly role: UserRole;
  readonly tenant: TenantContext;
  readonly iat: number;
  readonly exp: number;
}

/** Claims embedded in JWT for service accounts. */
export interface ServiceClaimsPayload {
  readonly sub: string;                     // service_name (e.g., "entropy-scheduler")
  readonly scope: 'SERVICE';
  readonly service_name: string;
  readonly iat: number;
  readonly exp: number;
}

export type ClaimsPayload = UserClaimsPayload | ServiceClaimsPayload;

// ─── Permission System ───────────────────────────────────────────────────────

/**
 * Permission categories.
 *
 * Constitutional enforcement: SPONSOR_STAKEHOLDER cannot have any of:
 * - corpus_mutation, emergency_trigger, emergency_acknowledge,
 *   canary_advance, parity_view, entropy_view, audit_view
 */
export type Permission =
  | 'corpus_read'
  | 'corpus_mutation'
  | 'campaign_approve'
  | 'override_create'
  | 'emergency_trigger'
  | 'emergency_acknowledge'
  | 'canary_advance'
  | 'parity_view'
  | 'entropy_view'
  | 'audit_view'
  | 'venue_manage'
  | 'enterprise_manage'
  | 'platform_admin';

// ─── Request Identity ─────────────────────────────────────────────────────────

/**
 * Verified identity attached to every authenticated request.
 * Passed to audit records — all mutations must carry this.
 */
export interface RequestIdentity {
  readonly user_id: string;                 // sub from JWT
  readonly scope: Scope;
  readonly role: UserRole | null;           // null for SERVICE scope
  readonly service_name: string | null;     // null for USER scope
  readonly tenant: TenantContext;
  readonly correlation_id: string;
}

// ─── JWT Verification Primitives ─────────────────────────────────────────────

/**
 * JWT verification error — thrown by verifyJWT on failure.
 * Shared so both cms-api and api-gateway can catch the same class.
 */
export class JWTVerificationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JWTVerificationError';
  }
}

/**
 * Verify a JWT and extract claims.
 *
 * NOTE: Signature verification is structural only (no crypto).
 * In production, replace with jose or jsonwebtoken for real signature checks.
 *
 * Dev mode: set JWT_VERIFY=false to skip the JWT_SECRET requirement and
 * accept unsigned dev tokens (generated by generateDevJWT()).
 */
export function verifyJWT(token: string): ClaimsPayload {
  const jwtVerify = process.env['JWT_VERIFY'] !== 'false';
  const secret = process.env['JWT_SECRET'];

  if (jwtVerify && !secret) {
    throw new JWTVerificationError(
      'JWT_SECRET not configured — set JWT_VERIFY=false for dev mode',
    );
  }

  if (!jwtVerify) {
    // eslint-disable-next-line no-console
    console.warn(
      '[jwt] WARNING: JWT signature verification disabled (JWT_VERIFY=false) — dev mode only',
    );
  }

  try {
    const parts = token.split('.');
    if (parts.length !== 3) {
      throw new JWTVerificationError('Invalid JWT format');
    }

    const payload = JSON.parse(
      Buffer.from(parts[1]!, 'base64url').toString('utf-8'),
    ) as Partial<ClaimsPayload>;

    if (!payload.sub || !payload.scope || !payload.exp) {
      throw new JWTVerificationError('Missing required JWT claims');
    }

    if (payload.exp < Math.floor(Date.now() / 1000)) {
      throw new JWTVerificationError('JWT expired');
    }

    if (payload.scope === 'USER') {
      const user = payload as Partial<UserClaimsPayload>;
      if (!user.role || !user.tenant) {
        throw new JWTVerificationError('USER scope requires role and tenant');
      }
      return payload as UserClaimsPayload;
    } else if (payload.scope === 'SERVICE') {
      const service = payload as Partial<ServiceClaimsPayload>;
      if (!service.service_name) {
        throw new JWTVerificationError('SERVICE scope requires service_name');
      }
      return payload as ServiceClaimsPayload;
    } else {
      throw new JWTVerificationError(`Unknown scope: ${String(payload.scope)}`);
    }
  } catch (err) {
    if (err instanceof JWTVerificationError) throw err;
    throw new JWTVerificationError(`JWT parse error: ${String(err)}`);
  }
}

/**
 * Generate a dev JWT for local testing.
 * Only valid when JWT_VERIFY=false — the signature is a placeholder.
 * Never use in production.
 */
export function generateDevJWT(
  sub: string,
  role: UserRole,
  enterpriseId: string,
  venueId?: string,
): string {
  const now = Math.floor(Date.now() / 1000);
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const claims: UserClaimsPayload = {
    sub,
    scope: 'USER',
    role,
    tenant: {
      enterprise_id: enterpriseId,
      regional_org_id: null,
      venue_id: venueId ?? null,
    },
    iat: now,
    exp: now + 86400,
  };
  const payloadEncoded = Buffer.from(JSON.stringify(claims)).toString('base64url');
  const sig = Buffer.from('dev-sig-not-verified').toString('base64url');
  return `${header}.${payloadEncoded}.${sig}`;
}

export function isUserClaims(claims: ClaimsPayload): claims is UserClaimsPayload {
  return claims.scope === 'USER';
}

export function isServiceClaims(claims: ClaimsPayload): claims is ServiceClaimsPayload {
  return claims.scope === 'SERVICE';
}
