BEGIN;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS zone_name VARCHAR(40) NOT NULL DEFAULT 'main';
ALTER TABLE screens   ADD COLUMN IF NOT EXISTS layout_template VARCHAR(40) NOT NULL DEFAULT 'fullscreen';
COMMIT;
